### ISSUE TITLE
Email-based authoring keys will be retired in LUIS on August 31, 2020

### ISSUE THREAD

**Issue by tomkerkhove** [azure-deprecation/dashboard#26]
***Update:** Deprecation is extended to August 31, 2020.*

Email-based authoring keys will be retired in Language Understanding Intelligent Service (LUIS) and is switching to Azure authoring resources.

**Deadline:** August 31, 2020
**Impacted Services:** Azure Cognitive Services / Language Understanding Intelligent Service (LUIS)
**More information:**
- [Steps to migrate to the Azure authoring resource](https://docs.microsoft.com/en-gb/azure/cognitive-services/luis/luis-migration-authoring-steps)
- [Migrate to an Azure resource authoring key](https://docs.microsoft.com/en-gb/azure/cognitive-services/luis/luis-migration-authoring)
- No public announcement was published

### Notice
Notice was sent out via email:
> ### Migrate to new Azure resources for Language Understanding authoring authentication
> *You're receiving this email because you use Language Understanding (also called LUIS), a part of the Azure Cognitive Services family.*
> 
> To provide more advanced security and authentication features for your Language Understanding apps, we're upgrading the authoring authentication from an email account to an Azure resource.
> 
> On **June 8, 2020**, your current authoring keys will be retired, and you'll need to start using Azure authoring resources. To avoid losing access to your Language Understanding apps, migrate to new resources by that date. 
> 
> The new Azure resources provide:
> •	Role-based access control (RBAC), allowing different users to have different > permissions.
> •	Azure Active Directory (Azure AD) authentication.
> •	Custom domains.
> 
> There's no charge for the Azure authoring resources, and authoring transactions will remain limited to 1 million per month and five per second.

### Impact

Access to LUIS apps will be lost in case of no migration

### Required Action

Migrate towards the Azure authoring resource approach as described [in this guide](https://docs.microsoft.com/en-gb/azure/cognitive-services/luis/luis-migration-authoring-steps).

### Contact

You can contact them via [Azure Support](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

**Comment by bartlannoeye** [comment]
Today's mail indicated a new date:

> On **August 31, 2020**, your current authoring keys will be retired, and you'll need to start using Azure authoring resources. To avoid losing access to your Language Understanding apps, migrate to new resources by that date.

**Comment by tomkerkhove** [comment]
Thanks Bart!
