### ISSUE TITLE
Azure Digital Twins Preview Gen 1 will be retired on December 31st, 2020

### ISSUE THREAD

**Issue by GlennColpaert** [azure-deprecation/dashboard#58]
A new version of the Azure Digital Twins service has been released. In light of the new service's expanded capabilities, the original Azure Digital Twins service will be retired by the end of the year 2020.

**Deadline:** December 31, 2020
**Impacted Services:** Azure Digital Twins
**More information:**
- https://docs.microsoft.com/en-us/previous-versions/azure/digital-twins/about-digital-twins

### Notice

> A new version of the Azure Digital Twins service has been released. In light of the new service's expanded capabilities, the original Azure Digital Twins service will be retired by the end of the year 2020.

### Impact

You will no longer be able to use Azure Digital Twins Preview v1

### Required Action

-  Migrate to the new Azure Digital Twins Preview

### Contact

Send email to adtpm@microsoft.com

### More information

N/A

**Comment by tomkerkhove** [comment]
Can you verify this please @olivierbloch, are there plans to post an update on https://azure.microsoft.com/en-us/updates/?

**Comment by olivierbloch** [comment]
Hi @tomkerkhove , I will reach out the the DT team and remind them to confirm.

**Comment by inesk-vt** [comment]
Hi Tom,

There are plans to post an update on this on Azure Updates, stay tuned for more info on this in the coming weeks. For the Impact outlined above, existing ADT v1 customers/partners will be able to continue leveraging the service when the preview updates launch. (note: the doc update above was inadvertently published, we haven't yet launched the announced ADT preview update).

Thanks Tom and look for an update on this very soon.

Ines

**Comment by GlennColpaert** [comment]
@inesk-vt thanks for the feedback! @tomkerkhove let's update this issue once the announcement comes. Maybe we can put it to unverified at the moment?

**Comment by tomkerkhove** [comment]
Sounds good to me and thanks for the input @olivierbloch @inesk-vt !

**Comment by GlennColpaert** [comment]
@inesk-vt just wondering if we could expect a separate update about the existing ADT v1 support (still the end of year 2020?) now that the ADT v2 has entered public preview?

**Comment by tomkerkhove** [comment]
Received official communication:

> ### Azure Digital Twins (2018) will be retired on 31 December 2020
> *You're receiving this email because you use the previous version (2018) of Azure Digital Twins (preview).* 
> 
> Azure Digital Twins (2018) will be retired on 31 December 2020. A new version of Azure Digital Twins was [released to public preview](https://azure.microsoft.com/blog/azure-digital-twins-powering-the-next-generation-of-iot-connected-solutions/) on 29 June 2020 and provides updates that weren't available in the previous version such as: 
> •	Flexible modelling and general graph topology 
> •	Richer Compute 
> •	Bring your own IoT Hub for easier integration 
> •	Improved scalability 
> 
> Azure Digital Twins public preview services will be free of charge until the new version becomes generally available (GA) later this year. 
>
> ### Required action 
> We recommend removing any Azure Digital Twins (2018) resources that are no longer being used and transitioning to the new service as soon as possible. 
> •	Get started with the transition by [checking Azure Digital Twins documentation](https://docs.microsoft.com/azure/digital-twins/overview-differences) 
> 
> ### More information 
> •	Watch [Azure Digital Twins deep dive webinar and Q/A](https://channel9.msdn.com/Shows/Internet-of-Things-Show/Deep-Dive-Azure-Digital-Twins-Updated-Capabilities) to learn more 
> If you have any questions, please [contact us](mailto:adtpm@microsoft.com).
